MyFirstDesign/Models/ErrorViewModel.cs
namespace MyFirstDesign.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyFirstDesign/Models/Require.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyFirstDesign.Models
{
    [Keyless]
    public class Require
    {
        [DisplayName ("Student Name")]
        public string StudentName { get; set; }
        [DisplayName ("Request Id")]
        public int RequestId{ get; set; } 
        public string Subject { get; set; } = null!;
        [DisplayName ("Created On")]
        public DateTime CreatedOn { get; set; }
        [DisplayName ("Created By")]
        public string CreatedBy { get; set; } = null!;
        [DisplayName("Due Date")]
        public DateTime DueDate { get; set; }
        public string Status { get; set; } = null!;
        public string Action { get; set; } = null!;
    }
}

MyFirstDesign/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstDesign.Models;
using System.Diagnostics;

namespace MyFirstDesign.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyFirstDesign/Controllers/RequireController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstDesign.Data;
using MyFirstDesign.Models;

namespace MyFirstDesign.Controllers
{
    public class RequireController : Controller
    {
        private readonly ApplicationDbContext _db;
        private object requireFromDb;

        public RequireController(ApplicationDbContext db)
        {
            _db = db;
        }

       

        public IActionResult Index()
        {
            IEnumerable<Require> objRequireList = _db.requires;
            return View(objRequireList);    
        }
    }
}

MyFirstDesign/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyFirstDesign/Views/Require/Index.cshtml
@model IEnumerable<Require>
@{
    ViewData["Title"] = "Index";
}
<div>
    <table id="RequsestId" class="display" style="width:100%">
        <thead>
            <tr>
                <td> Student Name </td>
                <td> Request Id </td>
                <td> Subject</td>
                <td> Created On </td>
                <td> Created By</td>
                <td> Due Date </td>
                <td> Status </td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var requires in Model)
            {
                <tr>
                    <td>@requires.StudentName </td>
                    <td> @requires.RequestId </td>
                    <td> @requires.Subject</td>
                    <td> @requires.CreatedOn </td>
                    <td> @requires.CreatedBy </td>
                    <td> @requires.DueDate </td>
                    <td>@requires.Status</td>
                    <td> @requires.Action</td>
                </tr>

            }
            
        <tbody>
    </table>
</div>

MyFirstDesign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstDesign</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/RequireStyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstDesign.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstDesign</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Require" asp-action="Index">RequireDetails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="align-text-bottom footer text-muted">
        <div class="container">
           Terms and Conditions| Copyrights &copy; 2021 iCent app| Powered by NeelTech inc.Canada <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>{
        $(document).ready(function() {
    $('#RequsestId').DataTable();
} );
    }
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/RequireJavaScript.js" asp-append-version="true"></script>
    <script src="~/js/Require1JavaScript.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>